--!strict
--!optimize 2

return {
    background = Color3.fromRGB(43, 34, 47),
    container = Color3.fromRGB(82, 65, 90),
    containerHigh = Color3.fromRGB(128, 102, 141),
    text = Color3.fromRGB(238, 221, 255),

    greenContainerHigh = Color3.fromRGB(105, 141, 107),
    onGreenContainer = Color3.fromRGB(229, 255, 232),

    redContainerHigh = Color3.fromRGB(141, 105, 105),
    onRedContainer = Color3.fromRGB(255, 229, 229),

    grayContainerHigh = Color3.fromRGB(84, 83, 95),
    onGrayContainer = Color3.fromRGB(211, 223, 244),

    accent = Color3.fromRGB(219, 154, 244)
}